directory: ~/Music
library: ~/Music/data/musiclibrary.blb

# Import Settings
import:
    write: yes
    copy: yes
    move: no

# Path Settings
paths:
    album: $albumartist/$album%aunique{}/$track $title
    singleton: _Singles/$albumartist/$title 

# Plugin Setup
plugins: fetchart embedart

fetchart:
    cautious: true
